//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCourseandResultManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tb> Admin_tb { get; set; }
        public virtual DbSet<AssignTeacher_tb> AssignTeacher_tb { get; set; }
        public virtual DbSet<Course_tb> Course_tb { get; set; }
        public virtual DbSet<Department_tb> Department_tb { get; set; }
        public virtual DbSet<Designation_tb> Designation_tb { get; set; }
        public virtual DbSet<Enroll_tb> Enroll_tb { get; set; }
        public virtual DbSet<Grade_tb> Grade_tb { get; set; }
        public virtual DbSet<Result_tb> Result_tb { get; set; }
        public virtual DbSet<Room_tb> Room_tb { get; set; }
        public virtual DbSet<RoomAllocation_tb> RoomAllocation_tb { get; set; }
        public virtual DbSet<Semester_tb> Semester_tb { get; set; }
        public virtual DbSet<Student_tb> Student_tb { get; set; }
        public virtual DbSet<StudentAttendance_tb> StudentAttendance_tb { get; set; }
        public virtual DbSet<Teacher_tb> Teacher_tb { get; set; }

        public System.Data.Entity.DbSet<UniversityCourseandResultManagement.Models.ClassRoomAllocate> ClassRoomAllocates { get; set; }

        public System.Data.Entity.DbSet<UniversityCourseandResultManagement.Models.Company> Companies { get; set; }
    }
}
