//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCourseandResultManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_tb()
        {
            this.StudentAttendance_tb = new HashSet<StudentAttendance_tb>();
        }
    
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentContact { get; set; }
        public System.DateTime RegDate { get; set; }
        public string StudentAddress { get; set; }
        public int DeptId { get; set; }
        public string RegisterNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendance_tb> StudentAttendance_tb { get; set; }
    }
}
