//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCourseandResultManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_tb
    {
        public int Id { get; set; }
        public string TeacherName { get; set; }
        public string TeacherAddress { get; set; }
        public string TracherEmail { get; set; }
        public string TracherContact { get; set; }
        public int DesignationId { get; set; }
        public int DeptId { get; set; }
        public decimal Credit { get; set; }
    }
}
